#!name=番茄小说 @zqzess
#!desc=广告屏蔽, version = 3.1
#！desc=https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever?tab=readme-ov-file

[Rule]
# 爱奇艺 PPS（可能有多余项）
DOMAIN-SUFFIX,ad.m.iqiyi.com,Reject
DOMAIN-SUFFIX,afp.iqiyi.com,Reject
DOMAIN-SUFFIX,api.cupid.iqiyi.com,Reject
DOMAIN-SUFFIX,c.uaa.iqiyi.com,Reject
DOMAIN-SUFFIX,cloudpush.iqiyi.com,Reject
DOMAIN-SUFFIX,cm.passport.iqiyi.com,Reject
DOMAIN-SUFFIX,emoticon.sns.iqiyi.com,Reject
DOMAIN-SUFFIX,gamecenter.iqiyi.com,Reject
DOMAIN-SUFFIX,hotchat-im.iqiyi.com,Reject
DOMAIN-SUFFIX,ifacelog.iqiyi.com,Reject
DOMAIN-SUFFIX,mbdlog.iqiyi.com,Reject
DOMAIN-SUFFIX,meta.video.qiyi.com,Reject
DOMAIN-SUFFIX,paopao.iqiyi.com,Reject
DOMAIN-SUFFIX,policy.video.iqiyi.com,Reject
DOMAIN-SUFFIX,rcd.iqiyi.com,Reject
DOMAIN-SUFFIX,cmts.iqiyi.com,Reject
DOMAIN-SUFFIX,data.video.qiyi.com,Reject
DOMAIN-SUFFIX,msg.71.am,Reject
DOMAIN-SUFFIX,msga.cupid.iqiyi.com,Reject
IP-CIDR,101.227.14.80/29,Reject
IP-CIDR,101.227.200.0/22,Reject
IP-CIDR,112.13.64.0/22,Reject
IP-CIDR,112.253.36.0/24,Reject
IP-CIDR,117.139.16.0/22,Reject
IP-CIDR,117.139.18.141/22,Reject
IP-CIDR,119.188.13.32/29,Reject
IP-CIDR,119.188.172.192/28,Reject
IP-CIDR,119.188.173.0/27,Reject
IP-CIDR,119.188.43.61/32,Reject
IP-CIDR,123.125.116.0/22,Reject
IP-CIDR,123.125.117.0/22,Reject
IP-CIDR,123.130.122.128/28,Reject
IP-CIDR,183.221.244.0/22,Reject
IP-CIDR,183.221.247.189/22,Reject
IP-CIDR,27.221.89.128/28,Reject
IP-CIDR,60.211.171.128/29,Reject
IP-CIDR,60.211.211.1/32,Reject

[URL Rewrite]

[MITM]
